spring:
  application:
    name: auth-server
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.0.194:5432/taco_cloud
      username: postgres
      password: "rXs-0z-4ODZEPmE"
      platform: postgresql
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

server:
  port: 9000
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.server.authorization: TRACE
    org.springframework.security.oauth2.core: TRACE
    org.springframework.security.oauth2.core.endpoint: TRACE
    org.springframework.security.oauth2.core.http.converter: TRACE
    org.springframework.security.web: TRACE
    root: INFO